financials/urls.py
from django.conf.urls import url
from . import views
from mindbalance import views as main_views


app_name = 'finance'

urlpatterns = [
    url(r'^balance/', views.balance, name='balance'),
    url(r'^balance_list/', views.balance_list, name='balance_list'),
    url(r'^balance_detail/(?P<slug>[\w-]+)/$', views.balance_detail, name='balance_detail'),
    url(r'^cashflow/', views.cashflow, name='cashflow'),
    url(r'^cashflow_list/', views.cashflow_list, name='cashflow_list'),
    url(r'^cashflow_detail/(?P<slug>[\w-]+)/$', views.cashflow_detail, name='cashflow_detail'),
    url(r'^income/', views.income, name='income'),
    url(r'^index/', main_views.index, name='index'),
]

mindbalance/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^financials/', include('financials.urls')),
    url(r'^about/', views.about),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financials/models.py
from django.db import models

# Create your models here.
class Stock_prediction(models.Model):
   title = models.CharField(max_length=140)
   uuid = models.CharField(max_length=36)
   start_month = models.IntegerField()
   start_day = models.IntegerField()
   start_year = models.IntegerField()
   end_month = models.IntegerField()
   end_day = models.IntegerField()
   end_year = models.IntegerField()
   ticker_symbol = models.CharField(max_length=20)




class Balance_sheet(models.Model):
   title = models.CharField(max_length=140)
   uuid = models.CharField(max_length=36)
   upload = models.FileField(upload_to='uploads/')

financials/forms.py
from django import forms
from.import models

class SearchStock(forms.ModelForm):
    class Meta:
        model = models.Stock_prediction
        fields = ['title', 'uuid', 'start_month', 'start_day', 'start_year', 'end_month', 'end_day', 'end_year', 'ticker_symbol']





class BalanceSheet(forms.ModelForm):
    class Meta:
        model = models.Balance_sheet
        fields = ['title', 'uuid', 'upload']

financials/views.py
from django.shortcuts import render
from django.http import HttpResponse
from.import forms
from .models import Stock_prediction, Balance_sheet
#from .util import randomUUID

import pandas as pd
import pandas_datareader.data as web
import yfinance as yf
yf.pdr_override()
"""
from sklearn import linear_model
import matplotlib.pyplot as plt
import io
import urllib, base64
"""
import datetime


# Create your views here.

def balance(request):
    if request.method == 'POST':
        form = forms.BalanceSheet(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            """
            instance = form.save(commit=False)
            instance.uuid = randomUUID
            instance.save()
            """
    else:
        form = forms.BalanceSheet()

    return render(request, 'balance.html', locals())

def balance_list(request):
    articles = Balance_sheet.objects.all().order_by('id');

    return render(request, 'balance_list.html', locals())

def balance_detail(request, slug):
    sheet = Balance_sheet.objects.get(title=slug)
    link = str(sheet.upload)
    file = open('media/' + link, 'rt')
    file_content = file.read()
    file.close()
    return HttpResponse(file_content, content_type="text/plain")



def cashflow(request):
    if request.method == 'POST':
        form = forms.SearchStock()
    else:
        form = forms.SearchStock()

    return render(request, 'stockpredict.html', locals())

def cashflow_list(request):
    articles = Stock_prediction.objects.all().order_by('id');
    return render(request, 'stockpredict_list.html', locals())

def cashflow_detail(request, slug):
    stock = Stock_prediction.objects.get(title=slug)

    title = str(stock.ticker_symbol)

    a = int(stock.start_year)
    b =int(stock.start_month)
    c = int(stock.start_day)

    d = int(stock.end_year)
    e = int(stock.end_month)
    f = int(stock.end_day)
    start = datetime.datetime(a, b, c)
    end = datetime.datetime(d, e, f)

    stock_pick = web.DataReader(title, start, end)
    df = pd.DataFrame(stock_pick)
    #web.seoption('display.max_columns', 500)
    html = df.to_html
    #html.head()

    return HttpResponse(html, content_type="text/plain")



def income(request):
    """
    dataframe = pd.read_fwf('media/uploads/brain_body')  # .txt file
    x_values = dataframe[['Brain']]
    y_values = dataframe[['Body']]

    # plt.plot(range(12))
    plt.scatter(x_values, y_values)
    plt.plot(x_values, x_values)
    fig = plt.gcf()

    buffer = io.BytesIO()
    fig.savefig(buffer, format='png')
    buffer.seek(0)
    string = base64.b64encode(buffer.read())
    uric = urllib.parse.quote(string)

    form = forms.SearchStock()

    if request.method == 'POST':
        form = forms.SearchStock()

        new_stock_serach = Stock_prediction()
        """
    start = datetime.datetime(2010, 1, 1)
    end = datetime.datetime(2017, 1, 11)

    df = web.DataReader("AAPL",  start, end)
    html = df.to_html



    return HttpResponse(html, content_type="text/plain")
    #return render(request, 'buysellhold.html', locals())

mindbalance/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def about(request):
    return HttpResponse('about')

templates/balance.html
<!DOCTYPE html>
<html>
  <head>
  <title>MindBalance</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
    h2.mainPage{justify-self: end; color: turquoise;position: absolute; right: 16px; top: 10px;
       }
  </style>
  </head>
  <body class="w3-light-grey" >
    <img src="data:image/png; base64,{{uria}}" alt="" height="500", width="500">

    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="w3-third ">
        <ul class="w3-ul w3-border w3-white w3-center w3-opacity w3-hover-opacity-off">
          <li class="w3-black w3-xlarge w3-padding-32">Balance Sheet Upload</li>
          <li class="w3-padding-16">TITLE: {{form.title}}</li>
          <li class="w3-padding-16">NOTE: {{form.uuid}}</li>
          <li class="w3-padding-16">PATH: {{form.upload}}</li>
          <li class="w3-padding-16">-</li>
          <li class="w3-padding-16">
            <h2>-</h2>
            <span class="w3-opacity">-</span>
          </li>
          <li class="w3-light-grey w3-padding-24">
              <a class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:balance_list' %}">Document List</a>
              <input class="w3-button w3-teal w3-padding-large w3-hover-black" type="submit" value="Save">
          </li>
        </ul>
      </div>
    <br>
    <h2 class="mainPage"><a href="{% url 'finance:index' %}">Main Page</a></h2>
  </body>
</html>

templates/balance_list.html
<!DOCTYPE html>
<html>
  <head>
  <title>MindBalance</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
    h2.mainPage{justify-self: end; color: white; position: absolute; right: 16px; top: 10px;
       }
  </style>
  </head>
  <body class="w3-light-grey">
    <h1 class="w3-teal">Articles List</h1>
    {% for article in articles %}
    <div class="w3-third w3-margin-bottom">
      <ul class="w3-ul w3-border w3-white w3-center w3-opacity w3-hover-opacity-off">
        <a href=""><li class="w3-black w3-xlarge w3-padding-32">{{ article.title }}</li></a>
        <li class="w3-padding-16">NOTE: {{ article.uuid }}</li>
        <li class="w3-padding-16">UPLOAD PATH: {{ article.upload }}</li>
        <li class="w3-padding-16">-</li>
        <li class="w3-padding-16">-</li>
        <li class="w3-padding-16">
          <h2>-</h2>
          <span class="w3-opacity">-</span>
        </li>
        <li class="w3-light-grey w3-padding-24">
            <a class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:balance_detail' slug=article.title %}">Analyze</a>
        </li>
      </ul>
    </div>
    {% endfor %}
    <h2 class="mainPage"><a href="{% url 'finance:index' %}">Main Page</a></h2>
  </body>
</html>

templates/buysellhold.html
<!DOCTYPE html>
<html>
  <head>
  <title>MindBalance</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <!--
    <img src="data:image/png; base64,{{uric}}" alt="" height="500", width="500">

    <form action="" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Present">
    </form>
  -->
  <table border = "1" cellpadding = "5" cellspacing = "5">
    <td>Dates</td>
    <td>Cumulated Values</td>
    <td>Actual Values</td>
    {% for i in data%}
    
    <tr>
        <td>{{i.Dates}}</td>
        <td>{{i.CumulatedValues}}</td>
        <td>{{i.ActualValues}}</td>
    </tr>

    {% endfor %}
</table>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<title>MindBalance</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey w3-content" style="max-width:1600px">

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container">
    <a href="#" onclick="w3_close()" class="w3-hide-large w3-right w3-jumbo w3-padding w3-hover-grey" title="close menu">
      <i class="fa fa-remove"></i>
    </a>
    <!--<img src="/w3images/avatar_g2.jpg" style="width:45%;" class="w3-round"><br><br>-->
    <h4><b>PORTFOLIO</b></h4>
    <p class="w3-text-grey">Let AI do the heavy lifting</p>
  </div>
  <div class="w3-bar-block">
    <a href="#portfolio" onclick="w3_close()" class="w3-bar-item w3-button w3-padding w3-text-teal"><i class="fa fa-th-large fa-fw w3-margin-right"></i>PORTFOLIO</a>
    <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>ABOUT</a>
    <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-padding"><i class="fa fa-envelope fa-fw w3-margin-right"></i>CONTACT</a>
  </div>
  <!--<div class="w3-panel w3-large">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>-->
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px">

  <!-- Header -->
  <header id="portfolio">
    <a href="#"><img src="/w3images/avatar_g2.jpg" style="width:65px;" class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
    <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i class="fa fa-bars"></i></span>
    <div class="w3-container">
    <h1><b>MindBalance</b></h1>
    <div class="w3-section w3-bottombar w3-padding-16">
    </div>
    </div>
  </header>



<div>



    <!-- Pricing Tables -->
    <!-- Balance Sheet -->
    <div class="w3-row-padding" style="margin:0 -16px">
      <div class="w3-third w3-margin-bottom">
        <ul class="w3-ul w3-border w3-white w3-center w3-opacity w3-hover-opacity-off">
          <li class="w3-black w3-xlarge w3-padding-32">Balance Sheet</li>
          <li class="w3-padding-16">Pick a Balance Sheet</li>
          <li class="w3-padding-16"> Upload it</li>
          <li class="w3-padding-16">ave it for later use</li>
          <li class="w3-padding-16"></li>
          <li class="w3-padding-16">
            <h2>-</h2>
            <span class="w3-opacity">-</span>
          </li>
          <li class="w3-light-grey w3-padding-24">
              <a class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:balance' %}">Select</a>
          </li>
        </ul>
      </div>

            <!-- Cashflow Statement -->
      <div class="w3-third w3-margin-bottom">
        <ul class="w3-ul w3-border w3-white w3-center w3-opacity w3-hover-opacity-off">
          <li class="w3-teal w3-xlarge w3-padding-32">Stock prediction</li>
          <li class="w3-padding-16">Pick a Stock</li>
          <li class="w3-padding-16">Choose a Time Frame</li>
          <li class="w3-padding-16">Wath the magic</li>
          <li class="w3-padding-16"></li>
          <li class="w3-padding-16">
            <h2>-</h2>
            <span class="w3-opacity">-</span>
          </li>
          <li class="w3-light-grey w3-padding-24">
              <a class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:cashflow' %}">select</a>
          </li>
        </ul>
      </div>

        <!-- Income Statement 
      <div class="w3-third">
        <ul class="w3-ul w3-border w3-white w3-center w3-opacity w3-hover-opacity-off">
          <li class="w3-black w3-xlarge w3-padding-32">Buy, Sell, or Hold</li>
          <li class="w3-padding-16">Web Design</li>
          <li class="w3-padding-16">Photography</li>
          <li class="w3-padding-16">Unlimited Storage</li>
          <li class="w3-padding-16">Endless Support</li>
          <li class="w3-padding-16">
            <h2>$ 7</h2>
            <span class="w3-opacity">per month</span>
          </li>
          <li class="w3-light-grey w3-padding-24">
              <a class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:income' %}">Select</a>
          </li>
        </ul>
      </div>-->
    </div>
  </div>

  <!-- Contact Section 

  <div class="w3-container w3-padding-large w3-grey">
    <h4 id="contact"><b>Contact Me</b></h4>
    <div class="w3-row-padding w3-center w3-padding-24" style="margin:0 -16px">
      <div class="w3-third w3-dark-grey">
        <p><i class="fa fa-envelope w3-xxlarge w3-text-light-grey"></i></p>
        <p>email@email.com</p>
      </div>
      <div class="w3-third w3-teal">
        <p><i class="fa fa-map-marker w3-xxlarge w3-text-light-grey"></i></p>
        <p>Cleveland, US</p>
      </div>
      <div class="w3-third w3-dark-grey">
        <p><i class="fa fa-phone w3-xxlarge w3-text-light-grey"></i></p>
        <p>555-555-5555</p>
      </div>
    </div>
    <hr class="w3-opacity">
    <form action="/action_page.php" target="_blank">
      <div class="w3-section">
        <label>Name</label>
        <input class="w3-input w3-border" type="text" name="Name" required>
      </div>
      <div class="w3-section">
        <label>Email</label>
        <input class="w3-input w3-border" type="text" name="Email" required>
      </div>
      <div class="w3-section">
        <label>Message</label>
        <input class="w3-input w3-border" type="text" name="Message" required>
      </div>
      <button type="submit" class="w3-button w3-black w3-margin-bottom"><i class="fa fa-paper-plane w3-margin-right"></i>Send Message</button>
    </form>
  </div>-->

  

  <div class="w3-black w3-center w3-padding-24">Powered by <a href="http://99.168.75.116:3000/" title="W3.CSS" target="_blank" class="w3-hover-opacity">DWare</a></div>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
}
</script>

</body>
</html>

templates/stockpredict.html
<!DOCTYPE html>
<html>
  <head>
  <title>MindBalance</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
    h2.mainPage{justify-self: end; color: turquoise; position: absolute; right: 16px; top: 10px;
       }
  </style>
  </head>
  <body class="w3-light-grey">
    {{testvar}}
    <img src="data:image/png; base64,{{uri}}" alt="" height="500", width="500">

    <form action="" method="POST">
      {% csrf_token %}
      {#form.as_p#}
      <div class="w3-third ">
        <ul class="w3-ul w3-border w3-white w3-center w3-opacity w3-hover-opacity-off">
          <li class="w3-black w3-xlarge w3-padding-32">Stock List Creation</li>
          <li class="w3-padding-16">Title: {{form.title}}</li>
          <li class="w3-padding-16">Uuid: {{form.uuid}}</li>
          <li class="w3-padding-16">Start month: {{form.start_month}}</li>
          <li class="w3-padding-16">Start day: {{form.start_day}}</li>
          <li class="w3-padding-16">Start year: {{form.start_year}}</li>
          <li class="w3-padding-16">End month: {{form.end_month}}</li>
          <li class="w3-padding-16">End day: {{form.end_day}}</li>
          <li class="w3-padding-16">End year: {{form.end_year}}</li>
          <li class="w3-padding-16">Ticker symbol: {{form.ticker_symbol}}</li>
          <li class="w3-padding-16">
            <h2>-</h2>
            <span class="w3-opacity">-</span>
          </li>
          <li class="w3-light-grey w3-padding-24">
              <a class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:cashflow_list' %}">Watch List</a>
              <input class="w3-button w3-teal w3-padding-large w3-hover-black" type="submit" value="Save" name="prediction">
          </li>
        </ul>
      </div>
    </form>
      <br>
      <h2 class="mainPage"><a href="{% url 'finance:index' %}">Main Page</a></h2>
  </body>
</html>

templates/stockpredict_list.html
<!DOCTYPE html>
<html>
  <head>
  <title>MindBalance</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}
    h2.mainPage{justify-self: end; color: white; position: absolute; right: 16px; top: 10px;
       }
  </style>
  </head>
  <body class="w3-light-grey">
    <h1 class="w3-teal">Watch List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="w3-third w3-margin-bottom">
          <ul class="w3-ul w3-border w3-white w3-center w3-opacity w3-hover-opacity-off">
            <a href=""><li class="w3-black w3-xlarge w3-padding-32">{{ article.title }}</li></a>
            <li class="w3-padding-16">ticker: {{ article.ticker_symbol }}</li>
            <li class="w3-padding-16">start year: {{ article.start_year }}</li>
            <li class="w3-padding-16">end year: {{ article.end_year }}</li>
            <li class="w3-padding-16">-</li>
            <li class="w3-padding-16">
              <h2>-</h2>
              <span class="w3-opacity">-</span>
            </li>
            <li class="w3-light-grey w3-padding-24">
              <button class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:index' %}">Main Page</button>
                <a class="w3-button w3-teal w3-padding-large w3-hover-black" href="{% url 'finance:cashflow_detail' slug=article.title %}">Analyze</a>
            </li>
          </ul>
        </div>
    {% endfor %}
    <h2 class="mainPage"><a href="{% url 'finance:index' %}">Main Page</a></h2>
    </div>
  </body>
</html>